insert into tipo_sede(nombre) values('SUCURSAL AGENCIAS LIMA');
insert into tipo_sede(nombre) values('SEDES LIMA');
insert into sede(nombre, codigo, tipo_sede_id, direccion, distrito_id,despacho) values('LIMA AGENCIAS', 'LAG', 1, 'Jr. Huancavelica', 1,0);
insert into sede(nombre, codigo, tipo_sede_id, direccion, distrito_id,despacho) values('LIMA AGENCIAS 2', 'LAG2', 1, 'Jr. Huancavelica', 2, 0);
insert into sede(nombre, codigo, tipo_sede_id, direccion, distrito_id,despacho) values('LA MOLINA', 'LMO', 2, 'Centenario 156', 1288, 1);
insert into sede(nombre, codigo, tipo_sede_id, direccion, distrito_id,despacho) values('SAN ISIDRO', 'SIS', 2, 'calle Las Begonias 469', 1305, 1);
insert into sede(nombre, codigo, tipo_sede_id, direccion, distrito_id,despacho) values('SANTA RAQUEL', 'STR', 2, 'La Arboleda 431', 1277, 1);
insert into sede(nombre, codigo, tipo_sede_id, direccion, distrito_id,despacho) values('LIMA', 'LIMA', 2, 'Jr. Lampa', 1275, 1);
insert into area(nombre, codigo, sede_id) values('COMERCIAL','C001',3);
insert into area(nombre, codigo, sede_id) values('PROYECTOS','C002',4);
insert into area(nombre, codigo, sede_id) values('CONTABILIDAD','C003',5);
insert into area(nombre, codigo, sede_id) values('COBRANZAS','C004',6);
insert into area(nombre, codigo, sede_id) values('TARJETAS DÉBITO','C005',1);
insert into area(nombre, codigo, sede_id) values('TARJETAS CRÉDITO','C006',1);
insert into area(nombre, codigo, sede_id) values('ADMINISTRACIÓN','C007',2);
insert into area(nombre, codigo, sede_id) values('OPERACIONES','C008',2);
insert into area(nombre, codigo, sede_id) values('UTD LMO','C009',3);
insert into area(nombre, codigo, sede_id) values('UTD SIS','C010',4);
insert into area(nombre, codigo, sede_id) values('UTD STR','C011',5);
insert into area(nombre, codigo, sede_id) values('UTD LIMA','C012',6);
insert into tipo_puesto(nombre) values('JEFE');
insert into tipo_puesto(nombre) values('OPERATIVO');
insert into tipo_puesto(nombre) values('ANALISTA');
insert into puesto(nombre, tipo_puesto_id, area_id) values('JEFE COMERCIAL', 1, 1);
insert into puesto(nombre, tipo_puesto_id, area_id) values('JEFE PROYECTOS', 1, 2);
insert into puesto(nombre, tipo_puesto_id, area_id) values('JEFE CONTABILIDAD', 1, 3);
insert into puesto(nombre, tipo_puesto_id, area_id) values('JEFE COBRANZAS', 1, 4);
insert into puesto(nombre, tipo_puesto_id, area_id) values('JEFE TARJETAS DÉBITO', 1, 5);
insert into puesto(nombre, tipo_puesto_id, area_id) values('JEFE TARJETAS CRÉDITO', 1, 6);
insert into puesto(nombre, tipo_puesto_id, area_id) values('JEFE ADMINISTRACIÓN', 1, 7);
insert into puesto(nombre, tipo_puesto_id, area_id) values('JEFE OPERACIONES', 1, 8);
insert into puesto(nombre, tipo_puesto_id, area_id) values('OPERATIVO UTD LMO', 2, 9);
insert into puesto(nombre, tipo_puesto_id, area_id) values('OPERATIVO UTD SIS', 2, 10);
insert into puesto(nombre, tipo_puesto_id, area_id) values('OPERATIVO UTD STR', 2, 11);
insert into puesto(nombre, tipo_puesto_id, area_id) values('OPERATIVO UTD LIMA', 2, 12);

-- OPERATIVOS UTD
insert into empleado(matricula, nombres) values('OHEREDIA', 'ORLANDO HEREDIA');
insert into empleado(matricula, nombres) values('CCAMPOS', 'CHRISTIAN CAMPOS');
insert into empleado(matricula, nombres) values('RSANTOS', 'RONALD SANTOS');
insert into empleado(matricula, nombres) values('CBALTAZAR', 'CESAR BALTAZAR');
-- JEFE BCP
insert into empleado(matricula, nombres) values('KVEGA', 'KATHERINE VEGA');
insert into empleado(matricula, nombres) values('KMACEDO', 'KATHELEEN MACEDO');
insert into empleado(matricula, nombres) values('KARRUE', 'KRYSTEL ARRUE');
insert into empleado(matricula, nombres) values('MCEVALLOS', 'MEDALIT CEVALLOS');

insert into puesto_empleado(puesto_id, empleado_id, fecha_asociado) values(1, 5, GETDATE());
insert into puesto_empleado(puesto_id, empleado_id, fecha_asociado) values(2, 6, GETDATE());
insert into puesto_empleado(puesto_id, empleado_id, fecha_asociado) values(3, 7, GETDATE());
insert into puesto_empleado(puesto_id, empleado_id, fecha_asociado) values(4, 8, GETDATE());
insert into puesto_empleado(puesto_id, empleado_id, fecha_asociado) values(9, 1, GETDATE());
insert into puesto_empleado(puesto_id, empleado_id, fecha_asociado) values(10, 2, GETDATE());
insert into puesto_empleado(puesto_id, empleado_id, fecha_asociado) values(11, 3, GETDATE());
insert into puesto_empleado(puesto_id, empleado_id, fecha_asociado) values(12, 4, GETDATE());
insert into buzon(nombre, area_id, activo) values('ORLANDO HEREDIA', 9, 1);
insert into buzon(nombre, area_id, activo) values('CHRISTIAN CAMPOS', 10, 1);
insert into buzon(nombre, area_id, activo) values('RONALD SANTOS', 11, 1);
insert into buzon(nombre, area_id, activo) values('CESAR BALTAZAR', 12, 1);
insert into buzon(nombre, area_id, activo) values('KATHERINE VEGA', 1, 1);
insert into buzon(nombre, area_id, activo) values('KATHELEEN MACEDO', 2, 1);
insert into buzon(nombre, area_id, activo) values('KRYSTEL ARRUE', 3, 1);
insert into buzon(nombre, area_id, activo) values('MEDALIT CEVALLOS', 4, 1);
insert into buzon_empleado(buzon_id, empleado_id, fecha_asociado) values(1,1,GETDATE());
insert into buzon_empleado(buzon_id, empleado_id, fecha_asociado) values(2,2,GETDATE());
insert into buzon_empleado(buzon_id, empleado_id, fecha_asociado) values(3,3,GETDATE());
insert into buzon_empleado(buzon_id, empleado_id, fecha_asociado) values(4,4,GETDATE());
insert into buzon_empleado(buzon_id, empleado_id, fecha_asociado) values(5,5,GETDATE());
insert into buzon_empleado(buzon_id, empleado_id, fecha_asociado) values(6,6,GETDATE());
insert into buzon_empleado(buzon_id, empleado_id, fecha_asociado) values(7,7,GETDATE());
insert into buzon_empleado(buzon_id, empleado_id, fecha_asociado) values(8,8,GETDATE());

